In [1]:
import torch

Основная структура данных для PyTorch -- это тензоры, по сути -- многомерные матрицы

In [2]:
torch.zeros([3, 4]) # Создает тензор 3 строки на 4 столбца заполненную нулями 

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [3]:
torch.ones([3, 4, 3]) # Создает тензор 3 строки на 4 столбца на 3 плоскости заполненную единицами 

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [4]:
torch.Tensor([[1, 2, 3, 4], # Создаем произвольный тензор в который передан list 
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [5]:
 x = torch.Tensor([[1, 2, 3, 4], 
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [6]:
x.size()# узнаем размерность тензора

torch.Size([3, 4])

In [7]:
x.shape # То же самое

torch.Size([3, 4])

In [8]:
x[0] # На элементы можно ссылаться

tensor([1., 2., 3., 4.])

In [9]:
x[:, 0]

tensor([1., 5., 9.])

In [10]:
x + 10 # Операции сложения, умножения и т.д выполняются к каждом элементу тензора

tensor([[11., 12., 13., 14.],
        [15., 16., 17., 18.],
        [19., 20., 21., 22.]])

In [11]:
x ** 2

tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.]])

In [12]:
y = torch.Tensor([[12, 11, 10, 9],
     [8, 7, 6, 5],
     [4, 3, 2, 1]])

In [13]:
x * y # Тензоры можно умножать и скалыдвать друг с другом только если они одного размера (ВСЕ КАК С МАТРИЦАМИ)

tensor([[12., 22., 30., 36.],
        [40., 42., 42., 40.],
        [36., 30., 22., 12.]])

In [14]:
x % y 

tensor([[1., 2., 3., 4.],
        [5., 6., 1., 3.],
        [1., 1., 1., 0.]])

In [15]:
a = torch.ones([5,4])
b = torch.Tensor([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16],
                  [17,18,19,20]])

In [16]:
a % b

tensor([[0., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
x > 3 # c тензорами возможно логические операции

tensor([[False, False, False,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [18]:
torch.sin(x) # Так тоже можно

tensor([[ 0.8415,  0.9093,  0.1411, -0.7568],
        [-0.9589, -0.2794,  0.6570,  0.9894],
        [ 0.4121, -0.5440, -1.0000, -0.5366]])

In [19]:
mask = x > 3 # Маской можно проводить сортировку по критеию заложнному в маске 

In [20]:
x[mask] # Так, все значения меньше 3 не будут выведены

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [21]:
y = x # Так x будет постоянно ссылаться на y и изменяться при изменении y
y[0,0] = 99
print(x)
print(y)

tensor([[99.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[99.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [22]:
y = x.clone() # Так х скопирует у  и не будет имзеняться пи изменении у
y[0,0] = 99
print(x)
print(y)

tensor([[99.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[99.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [23]:
x = x.double() # В тензоре заключены дробный значения (Float). Теперь вместо 32 бит на каждое число выделяется 64 бита

In [24]:
import numpy as np

In [25]:
x = np.array([[1, 2, 3, 4],
             [1, 2, 3, 4]])

In [26]:
x = torch.from_numpy(x)

In [27]:
x # Вот так вот. Из массива в тензор

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4]], dtype=torch.int32)

In [28]:
x = x.numpy()

In [29]:
x # И обратно

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [30]:
x = torch.rand([2, 3]) # Тензор 2 на 3 заполненный псевдослуайными числами

In [31]:
torch.cuda.is_available() # через юпитер нельзя запускать код на видеокарте

False

SyntaxError: can't assign to operator (<ipython-input-34-f51855215cd2>, line 1)