In [47]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [48]:
x = torch.tensor([[1, 2, 3, 4],
                 [5, 6 , 7, 8],
                 [9, 10, 11, 12]], dtype = float, requires_grad = True)

In [49]:
function = 10 * (x ** 2).sum() # на выходе получаем скаляр
function.backward() # Операция по взятию производной
print(x.grad, '<- gradient') # Результат операции backward хранится как оператор x и вызывается x.grad 

tensor([[ 20.,  40.,  60.,  80.],
        [100., 120., 140., 160.],
        [180., 200., 220., 240.]], dtype=torch.float64) <- gradient


In [50]:
x, function

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]], dtype=torch.float64, requires_grad=True),
 tensor(6500., dtype=torch.float64, grad_fn=<MulBackward0>))

In [51]:
x.grad
x.data -= 0.001 * x.grad # x.data это тот же тензор, но он не позволяет брать градиент.
                         #Это нужно для корректного вычисления последующих итераций

In [52]:
x.grad.zero_() # При последеющих итерациях градиент будет накапливаться. Для избежания этого, необходимо каждый раз обнулять x.grad 

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)

In [53]:
x = torch.tensor([8, 8], dtype = float, requires_grad = True)

optimizer = torch.optim.SGD([x], lr  = 0.001)

In [54]:
def function_parabola(variable):
    return 10 * (variable ** 2).sum()

In [55]:
def make_gradient_step(function, variable):
    function_result = function(variable)
    function_result.backward()
    optimizer.step()
    optimizer.zero_grad()

In [56]:
for i in range(500):
    make_gradient_step(function_parabola, x)
  

Задача: Реализовать поиск производной

In [24]:
w = torch.tensor([[5,10],
                  [1,2]], dtype = float, requires_grad = True)
alpha = 0.001

optimizer = torch.optim.SGD([w], lr  = alpha)
function = torch.prod(torch.log(torch.log(w + 7)))
function.backward()
optimizer.step()
optimizer.zero_grad()

In [19]:
print(w.grad)

tensor([[0.0201, 0.0109],
        [0.0449, 0.0351]], dtype=torch.float64)


In [25]:
for i in range(500):
    # critical: calculate the function inside the loop
    function = (w + 7).log().log().prod()
    function.backward()


print(w) # Код для самопроверки, не забудьте закомментировать перед

tensor([[4.9899, 9.9946],
        [0.9775, 1.9824]], dtype=torch.float64, requires_grad=True)
